# Generated by Django 4.2.13 on 2024-05-27 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='review',
        ),
    ]
