# Generated by Django 4.2.13 on 2024-06-30 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_minibarimage_bathroomimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroomimage',
            name='room',
        ),
        migrations.RemoveField(
            model_name='minibarimage',
            name='room',
        ),
    ]
