# Generated by Django 4.2.13 on 2024-06-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_reservation_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
