# Generated by Django 4.2.13 on 2024-06-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_reservation_updated_on_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
