# Generated by Django 4.2.13 on 2024-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_remove_bathroomimage_room_remove_minibarimage_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status_changed',
            field=models.BooleanField(default=False),
        ),
    ]
