# Generated by Django 4.2.13 on 2024-06-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_reservation_featured_image_room_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='featured_image',
        ),
    ]
